### ISSUE TITLE
Problem with compilation 

### ISSUE THREAD

**Issue by dariast1978** [syl22-00/pocketsphinx.js#122]
**Dear syl22-00 , i am mexican researcher. I am trying to compile pocketsphinx.js  but i got this error:** 

PS D:\DOCS\Desktop\libreriasonido\finallibreria\pocketsphinx.js\build8> mingw32-make
[100%] Built target pocketsphinx
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: posix_spawn_file_actions_init

**after a while i got :**

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Traceback (most recent call last):
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\\emcc", line 11, in <module>
    python_selector.run(__file__)
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\emcc.py", line 1864, in run
    optimizer.flush()
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\emcc.py", line 241, in flush
    self.run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\emcc.py", line 276, in run_passes
    output_filename=self.in_temp(os.path.basename(final) + '.jsopted.js'))
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\shared.py", line 2086, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\js_optimizer.py", line 557, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\tempfiles.py", line 93, in run_and_clean
    return func()
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\js_optimizer.py", line 557, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "D:\DOCS\Desktop\libreriasonido\emsdk\emscripten\1.37.38\tools\js_optimizer.py", line 500, in run_on_js
    assert proc.returncode == 0
AssertionError
CMakeFiles\pocketsphinx.js.dir\build.make:56: recipe for target 'CMakeFiles/pocketsphinx.js' failed
mingw32-make[2]: *** [CMakeFiles/pocketsphinx.js] Error 1
CMakeFiles\Makefile2:103: recipe for target 'CMakeFiles/pocketsphinx.js.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/pocketsphinx.js.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

 **Thank you for any help, in advanced**

**Comment by dariast1978** [comment]
I forgot to tell you that i am trying to compile pocketsphinx.js using windows.
