### ISSUE TITLE
Can't install with npm

### ISSUE THREAD

**Issue by skuzzymiglet** [syl22-00/pocketsphinx.js#139]
I'm on linux trying to install with `npm i -g pocketsphinx` with the prefix `~/.npm-global/`. `cmake-js compile` fails:

`~/.npm/_logs/2020-03-22T08_34_50_002Z-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'pocketsphinx' ]
2 info using npm@6.14.3
3 info using node@v13.11.0
4 verbose npm-session a219c8b3817587d6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/pocketsphinx 271ms (from cache)
8 silly pacote tag manifest for pocketsphinx@latest fetched in 280ms
9 timing stage:loadCurrentTree Completed in 314ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule pocketsphinx@5.0.7 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 6ms
18 timing stage:loadIdealTree Completed in 10ms
19 silly currentTree lib
20 silly idealTree lib
20 silly idealTree └── pocketsphinx@5.0.7
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 4ms
23 silly diffTrees action count 1
24 silly diffTrees add pocketsphinx@5.0.7
25 silly decomposeActions action count 8
26 silly decomposeActions fetch pocketsphinx@5.0.7
27 silly decomposeActions extract pocketsphinx@5.0.7
28 silly decomposeActions preinstall pocketsphinx@5.0.7
29 silly decomposeActions build pocketsphinx@5.0.7
30 silly decomposeActions install pocketsphinx@5.0.7
31 silly decomposeActions postinstall pocketsphinx@5.0.7
32 silly decomposeActions finalize pocketsphinx@5.0.7
33 silly decomposeActions refresh-package-json pocketsphinx@5.0.7
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /home/skuzzymiglet/.npm/_locks correctMkdir not in flight; initializing
37 verbose lock using /home/skuzzymiglet/.npm/_locks/staging-cde31dfc532936c6.lock for /home/skuzzymiglet/.npm-global/lib/node_modules/.staging
38 silly doParallel extract 1
39 silly extract pocketsphinx@5.0.7
40 silly tarball trying pocketsphinx@latest by hash: sha1-dUwktQehepSJPiB7kAzI1mRV6EM=
41 silly extract pocketsphinx@latest extracted to /home/skuzzymiglet/.npm-global/lib/node_modules/.staging/pocketsphinx-5000093b (22ms)
42 timing action:extract Completed in 26ms
43 silly doReverseSerial unbuild 8
44 silly doSerial remove 8
45 silly doSerial move 8
46 silly doSerial finalize 8
47 silly finalize /home/skuzzymiglet/.npm-global/lib/node_modules/pocketsphinx
48 timing action:finalize Completed in 5ms
49 silly doParallel refresh-package-json 1
50 silly refresh-package-json /home/skuzzymiglet/.npm-global/lib/node_modules/pocketsphinx
51 timing action:refresh-package-json Completed in 10ms
52 silly doParallel preinstall 1
53 silly preinstall pocketsphinx@5.0.7
54 info lifecycle pocketsphinx@5.0.7~preinstall: pocketsphinx@5.0.7
55 timing action:preinstall Completed in 2ms
56 silly doSerial build 8
57 silly build pocketsphinx@5.0.7
58 info linkStuff pocketsphinx@5.0.7
59 silly linkStuff pocketsphinx@5.0.7 has /home/skuzzymiglet/.npm-global/lib/node_modules as its parent node_modules
60 silly linkStuff pocketsphinx@5.0.7 is part of a global install
61 silly linkStuff pocketsphinx@5.0.7 is installed into a global node_modules
62 silly linkStuff pocketsphinx@5.0.7 is installed into the top-level global node_modules
63 timing action:build Completed in 1ms
64 silly doSerial global-link 8
65 silly doParallel update-linked 0
66 silly doSerial install 8
67 silly install pocketsphinx@5.0.7
68 info lifecycle pocketsphinx@5.0.7~install: pocketsphinx@5.0.7
69 verbose lifecycle pocketsphinx@5.0.7~install: unsafe-perm in lifecycle true
70 verbose lifecycle pocketsphinx@5.0.7~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/skuzzymiglet/.npm-global/lib/node_modules/pocketsphinx/node_modules/.bin:/home/skuzzymiglet/.npm-global/lib/node_modules/.bin:/opt/android-sdk//tools:/opt/android-sdk//platform-tools:/home/skuzzymiglet/go/bin:/home/skuzzymiglet/.local/bin:/home/skuzzymiglet/.gem/ruby/2.6.0/bin:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/:/usr/lib/jvm/java-11-openjdk/bin/:node_modules/.bin/:/home/skuzzymiglet/flutter/bin/:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/emulator:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/android-sdk/tools/bin/
71 verbose lifecycle pocketsphinx@5.0.7~install: CWD: /home/skuzzymiglet/.npm-global/lib/node_modules/pocketsphinx
72 silly lifecycle pocketsphinx@5.0.7~install: Args: [ '-c', 'cmake-js compile' ]
73 silly lifecycle pocketsphinx@5.0.7~install: Returned: code: 1  signal: null
74 info lifecycle pocketsphinx@5.0.7~install: Failed to exec install script
75 timing action:install Completed in 2147ms
76 verbose unlock done using /home/skuzzymiglet/.npm/_locks/staging-cde31dfc532936c6.lock for /home/skuzzymiglet/.npm-global/lib/node_modules/.staging
77 timing stage:rollbackFailedOptional Completed in 13ms
78 timing stage:runTopLevelLifecycles Completed in 2540ms
79 verbose stack Error: pocketsphinx@5.0.7 install: `cmake-js compile`
79 verbose stack Exit status 1
79 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
79 verbose stack     at EventEmitter.emit (events.js:315:20)
79 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
79 verbose stack     at ChildProcess.emit (events.js:315:20)
79 verbose stack     at maybeClose (internal/child_process.js:1026:16)
79 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
80 verbose pkgid pocketsphinx@5.0.7
81 verbose cwd /
82 verbose Linux 5.5.10-arch1-1
83 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "pocketsphinx"
84 verbose node v13.11.0
85 verbose npm  v6.14.3
86 error code ELIFECYCLE
87 error errno 1
88 error pocketsphinx@5.0.7 install: `cmake-js compile`
88 error Exit status 1
89 error Failed at the pocketsphinx@5.0.7 install script.
89 error This is probably not a problem with npm. There is likely additional logging output above.
90 verbose exit [ 1, true ]
```

**Comment by syl22-00** [comment]
You are probably referring to pocketsphinx (https://github.com/cmusphinx/pocketsphinx). This repo is pocketsphinx.js, a port of pocketsphinx to JavaScript/WebAssembly.
