### ISSUE TITLE
Use dictionary words from .dict instead of wordList

### ISSUE THREAD

**Issue by 140462E** [syl22-00/pocketsphinx.js#72]
Hi, I'm new to this and I do not have any idea on how to use the words from the .dict file that I have compiled with pocketsphinx.js instead of the wordList array in the sample webapp. Is it possible?

**Comment by nshmyrev** [comment]
No, it is not possible. You have to specify a word list. 

If you want to run large vocabulary decoding, you have to specify a language model and it will be quite slow, probably too slow and inaccurate for the javascript inside the browser.

**Comment by syl22-00** [comment]
If your question was just whether you could add words using a dictionary file rather than addWords, then the answer is yes. The bottom line is that when you add a language model (a grammar or a statistical language model), the words should all be known by pocketsphinx, either added via addWords or via a dictionary file.

**Comment by Je4hel** [comment]
Hi, I'm answering this old issue because I would need the same thing as ghost. @syl22-00 You say it's possible to add the words from a dictionary file, but how do you do so? I am using a french language model provided by CMU Sphinx and would like to use their dictionary to transcript all audio that is recorder. How should I do that?

I believe that I already load the dictionary:
```
postRecognizerJob(
        {
            command: 'initialize', data: [
                ["-hmm", "cmusphinx-fr-ptm-5.2"],
                ["-fwdflat", "no"],
                ["-dict", "cmusphinx-fr-ptm-5.2/fr.dict"]
            ]
        },
        function ()
        {
            if (recorder) recorder.consumers = [recognizer];
            setKeywordFromSelect();
        }
    );
```
And I lazy load the file here:
```
postRecognizerJob({
        command: 'lazyLoad',
        data: {
            folders: [["/", "cmusphinx-fr-ptm-5.2"]],
            files: [
                ["/cmusphinx-fr-ptm-5.2", "means", "../cmusphinx-fr-ptm-5.2/means"],
                ["/cmusphinx-fr-ptm-5.2", "variances", "../cmusphinx-fr-ptm-5.2/variances"],
                ["/cmusphinx-fr-ptm-5.2", "transition_matrices", "../cmusphinx-fr-ptm-5.2/transition_matrices"],
                ["/cmusphinx-fr-ptm-5.2", "mdef", "../cmusphinx-fr-ptm-5.2/mdef"],
                ["/cmusphinx-fr-ptm-5.2", "feat.params", "../cmusphinx-fr-ptm-5.2/feat.params"],
                ["/cmusphinx-fr-ptm-5.2", "mixture_weights", "../cmusphinx-fr-ptm-5.2/mixture_weights"],
                ["/cmusphinx-fr-ptm-5.2", "noisedict", "../cmusphinx-fr-ptm-5.2/noisedict"],
                ["/cmusphinx-fr-ptm-5.2", "fr.dict", "../cmusphinx-fr-ptm-5.2/fr.dict"]
            ]
        }
    });
```

Then I don't understand why I still have to set the keywords one by one to be recognized.

Also I have an unrelated question: is it possible to run PocketSphinx.js on an audio file (such as webm) after it was recorded instead of while it is recorded?

Thank you for your help!

**Comment by syl22-00** [comment]
One of the components of a speech recognizer like pocketsphinx is the pronunciation dictionary. It tells the engine how words are pronounced. As you can see in the dictionary file, it matches words with strings of phonemes. The words of the pronunciation dictionary can be given at init time via a dictionary file (the -dict argument) or at runtime using the addWords function.

The recognizer will also need a language model which tell which words to expect and how they might be combined. There are several types: grammars, statistical language models, key phrases. No matter which one you use, all the words in your language model must have been added previously in the dictionary. So you need both, always.

As for getting audio samples from a video or audio file, you can use html5 media elements and the web audio API. check out this comment: https://github.com/syl22-00/pocketsphinx.js/issues/105#issuecomment-318175936

**Comment by syl22-00** [comment]
No, the HMM (-hmm) is the acoustic model, it tells the recognizer how phones are pronounced. Language models can be added via -lm (statistical language models), -fsg (FSG grammar), -keyphrase, or their equivalents at runtime through the API.

**Comment by Je4hel** [comment]
My bad, I didn't catch that. I added the language model that CMU Sphinx provides for french. But now I have an error about memory size. I guess I have to recompile with different settings. Could you provide more information about that?

Here is the error that happens during initialization:
```
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 100663296, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (http://localhost:3030/js/pocketsphinx.js:1:3106684)
    at stackTrace (http://localhost:3030/js/pocketsphinx.js:1:3106867)
    at abort (http://localhost:3030/js/pocketsphinx.js:19:5309)
    at abortOnCannotGrowMemory (http://localhost:3030/js/pocketsphinx.js:1:3107660)
    at enlargeMemory (http://localhost:3030/js/pocketsphinx.js:1:3108105)
    at Function.dynamicAlloc [as alloc] (http://localhost:3030/js/pocketsphinx.js:1:3096577)
    at _sbrk (http://localhost:3030/js/pocketsphinx.js:1:3431516)
    at iz (http://localhost:3030/js/pocketsphinx.js:10:34315)
    at kz (http://localhost:3030/js/pocketsphinx.js:10:45151)
    at St (http://localhost:3030/js/pocketsphinx.js:11:5905)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by syl22-00** [comment]
You can increase the heap size (-s TOTAL_MEMORY=... in CMakeLists.txt) but I am not sure how fast  statistical language models can run in the browser. If you can, try using grammars.

**Comment by Je4hel** [comment]
In fact I am developing an Electron app, and I don't need this process to be synchronous, plus I will only be working on small audio files (some seconds each), so speed is not that critical.

What I need is just a transcript of the words said by the user. They will be prompted a word to read and I need to make sure they said it. But I can't just use KWS because I also need to know if it is the first word they said. So I though I would just transcribe what they say and check if the first word is what I expected. This means that they won't be saying sensible sentences, just a word, maybe some hesitating sounds before that - and I need to detect that too.

I thought a grammar wasn't sufficient for that purpose. What do you think?

**Comment by syl22-00** [comment]
Yes, grammars would be a better choice.
